# See http://docs.travis-ci.com/user/languages/csharp/ for details

language: csharp
mono: none
dotnet: 2.1.400
dist: trusty

script:
  - dotnet build src/NodaTime.Serialization.Test -f netcoreapp2.0
  - dotnet run -p src/NodaTime.Serialization.Test -f netcoreapp2.0
